# Generated by Django 4.2.1 on 2023-06-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='editing',
            field=models.BooleanField(default=False),
        ),
    ]
