# Generated by Django 4.2.1 on 2023-06-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_audiofile_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('conversation_type', models.CharField(max_length=255)),
                ('audio_recognition_model_id', models.CharField(choices=[('whisper-1', 'whisper')], max_length=255)),
                ('system_prompt', models.TextField()),
                ('ai_model_id', models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5'), ('gpt-3.5-turbo-16k', 'GPT-3.5-16k'), ('gpt4', 'GPT4')], max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('presence_penalty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('form_template', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.formtemplate')),
            ],
        ),
    ]
