# Generated by Django 4.2.1 on 2023-06-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_audiofile_file_path_audiofile_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formresponse',
            name='response',
            field=models.TextField(default='Processing...'),
        ),
    ]
