# Generated by Django 4.2.1 on 2023-06-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_formresponse_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_template_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
