# Generated by Django 4.2.1 on 2023-06-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_form_form_template_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='transcript',
            field=models.TextField(default=''),
        ),
    ]
