# Generated by Django 4.2.1 on 2023-06-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='ai_model_id',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'GPT-3.5'), ('gpt-3.5-turbo-16k', 'GPT-3.5-16k'), ('gpt4', 'GPT4')], default='gpt-3.5-turbo', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='audio_recognition_model_id',
            field=models.CharField(choices=[('whisper-1', 'whisper')], default='whisper-1', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='conversation_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.CharField(default='english', max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='presence_penalty',
            field=models.DecimalField(decimal_places=2, default=-0.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='system_prompt',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='settings',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
    ]
