# Generated by Django 4.2.1 on 2023-06-17 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_formsettings_formconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formconfig',
            name='presence_penalty',
            field=models.DecimalField(decimal_places=1, default=-0.2, max_digits=3, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-2)]),
        ),
        migrations.AlterField(
            model_name='formconfig',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0.2, max_digits=3, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(-2)]),
        ),
    ]
